### ISSUE TITLE
ETA for docs/demo?

### ISSUE THREAD

**Issue by coniel** [Fandora/mdl-react#73]
Looking forward to trying this out, it seems like you guys are advancing fast.

Is there any ETA for documentation or a working demo? I tried running the example but it doesn't work (app.js file is missing).

**Comment by seal789ie** [comment]
You can find the demo in http://fandora.github.io/mdl-react/

**Comment by coniel** [comment]
Great, thanks a lot for the hard work!

**Comment by diogovk** [comment]
Wow that's pretty cool!
